matrixを導入

diff --git a/.github/workflows/build-and-release.yml b/.github/workflows/build-and-release.yml
--- a/.github/workflows/build-and-release.yml
+++ b/.github/workflows/build-and-release.yml
@@ -17,8 +17,20 @@ env:
 jobs:
   ci:
     name: パッケージのビルドとテスト
-    runs-on: windows-latest
+
+    strategy:
+      fail-fast: false
+      matrix:
+        vm_image: [ubuntu-latest, windows-latest]
+        framework_version: [net48, net6.0, net7.0]
+        exclude:
+          - vm_image: ubuntu-latest
+            framework_version: net48
+
+    runs-on: ${{ matrix.vm_image }}
+
     if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
+
     env:
       DOTNET_NOLOGO: true
       DOTNET_CLI_TELEMETRY_OPTOUT: true
@@ -30,95 +42,149 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: .NET SDK のセットアップ
-        uses: actions/setup-dotnet@v3
-        with:
-          dotnet-version: | 
-            6.0.x
-            7.0.x
-          dotnet-quality: 'ga'
+      - id: application-build
+        name: アプリケーションのビルド
+        run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }} --framework ${{ matrix.framework_version }} --verbosity minimal > build-result.txt
 
-      - name: NuGet パッケージの復元
-        run: dotnet restore
-
-      - name: アプリケーションのビルド
-        run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}
+      - name: ビルド結果の表示
+        shell: bash
+        if: ${{ success() || (failure() && steps.application-build.conclusion == 'failure') }}
+        run: |
+          echo '## Build Result :gear:' >> $GITHUB_STEP_SUMMARY
+          cat build-result.txt | sed -n -e 's/^/> /p' >> $GITHUB_STEP_SUMMARY
 
       - name: 単体テストの実行
         id: execute-unit-test
         continue-on-error: true
-        run: dotnet test --no-build --verbosity normal --configuration ${{ env.BUILD_CONFIGURATION }} /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=cobertura > testResult.txt
+        run: dotnet test --no-build --logger trx --verbosity normal --configuration ${{ env.BUILD_CONFIGURATION }} --framework ${{ matrix.framework_version }} /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=cobertura > testResult.txt
 
-      - name: テスト結果のアップロード
-        uses: actions/upload-artifact@v3
+      - name: テスト結果の表示(ヘッダー)
+        shell: bash
+        if: ${{ success() || (failure() && steps.execute-unit-test.conclusion == 'failure') }}
+        run: |
+          echo '## Test Result :memo:' >> $GITHUB_STEP_SUMMARY
+
+      - name: テスト結果の表示(本体)
+        uses: dorny/test-reporter@v1
+        if: ${{ success() || (failure() && steps.execute-unit-test.conclusion == 'failure') }}
         with:
-          name: TestResult
-          path: testResult.txt
-          retention-days: 7
+          name: '${{ matrix.framework_version }} on ${{ matrix.vm_image }} test results'
+          path: '**/TestResults/*.trx'
+          path-replace-backslashes: 'true'
+          reporter: 'dotnet-trx'
+          only-summary: 'false'
+          list-suites: 'all' # all / failed
+          list-tests: 'all' # all / failed / none
+          max-annotations: '10'
+          fail-on-error: 'true'
+
+      - id: create-coverage-report
+        name: コードカバレッジレポートの解析
+        uses: danielpalme/ReportGenerator-GitHub-Action@5
+        if: ${{ success() || (failure() && steps.execute-unit-test.conclusion == 'failure') }}
+        with:
+          reports: '**/TestResults/coverage.*.cobertura.xml'
+          targetdir: 'CoverageReport'
+          reporttypes: 'MarkdownSummary;MarkdownSummaryGithub;MarkdownDeltaSummary'
 
       - name: コードカバレッジレポートのアップロード
         uses: actions/upload-artifact@v3
+        if: ${{ success() || (failure() && steps.create-coverage-report.conclusion == 'failure') }}
         with:
-          name: CoverageReports
-          path: tests/Test.TsunaCan.HelloWorld/TestResults/
+          name: CoverageReport
+          path: CoverageReport
           retention-days: 7
 
-  ci-report:
-    name: パッケージのビルドとテストレポート表示
-    runs-on: ubuntu-latest
-    needs: ci
+#      - name: ビルド結果のアップロード
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: BuildResult
+#          path: build-result.txt
+#          retention-days: 7
 
-    steps:
-      - name: テスト結果のダウンロード
-        uses: actions/download-artifact@v3
-        with:
-          name: TestResult
+#      - name: テスト結果のアップロード
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: TestResult
+#          path: testResult.txt
+#          retention-days: 7
 
-      - name: コードカバレッジレポートのダウンロード
-        uses: actions/download-artifact@v3
-        with:
-          name: CoverageReports
-          path: coverage-reports
+#      - name: テスト結果のアップロード2
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: TestResult2
+#          path: tests/Test.TsunaCan.HelloWorld/TestResults/*.trx
+#          retention-days: 7
 
-      - name: 単体テストの結果表示
-        shell: bash
-        run: |
-          cat testResult.txt
-          if [ '${{ steps.execute-unit-test.outcome }}' == 'failure' ]; then
-            exit 1
-          fi
-          echo '# Build Result :gear:' >> $GITHUB_STEP_SUMMARY
-          cat testResult.txt | sed -n -e '/Done/,/Elapsed/p' >> $GITHUB_STEP_SUMMARY
-          echo '' >> $GITHUB_STEP_SUMMARY
-          echo '# Test Result :memo:' >> $GITHUB_STEP_SUMMARY
-          cat testResult.txt | sed -n -e '/A total of/,/Passed/p' >> $GITHUB_STEP_SUMMARY
-          echo '' >> $GITHUB_STEP_SUMMARY
+#      - name: コードカバレッジレポートのアップロード
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: CoverageReports
+#          path: tests/Test.TsunaCan.HelloWorld/TestResults/coverage.*.cobertura.xml
+#          retention-days: 7
 
-      - name: コードカバレッジのサマリー作成
-        uses: irongut/CodeCoverageSummary@v1.3.0
-        with:
-          filename: coverage-reports/**/coverage.*.cobertura.xml
-          badge: true
-          fail_below_min: true
-          format: markdown
-          hide_branch_rate: false
-          hide_complexity: false
-          indicators: true
-          output: both
-          thresholds: '60 80'
+#  ci-report:
+#    name: パッケージのビルドとテストレポート表示
+#    runs-on: ubuntu-latest
+#    needs: ci
 
-      - name: コードカバレッジの結果表示
-        shell: bash
-        run: |
-          echo '# Coverage :triangular_ruler:' >> $GITHUB_STEP_SUMMARY
-          cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
+#    steps:
+#      - name: ビルド結果のダウンロード
+#        uses: actions/download-artifact@v3
+#        with:
+#          name: BuildResult
 
-      - name: コードカバレッジの結果をPull-requestに表示
-        uses: marocchino/sticky-pull-request-comment@v2
-        if: github.event_name == 'pull_request'
-        with:
-          recreate: true
-          path: code-coverage-results.md
+#      - name: テスト結果のダウンロード
+#        uses: actions/download-artifact@v3
+#        with:
+#          name: TestResult
+
+#      - name: テスト結果のダウンロード2
+#        uses: actions/download-artifact@v3
+#        with:
+#          name: TestResult2
+
+#      - name: コードカバレッジレポートのダウンロード
+#        uses: actions/download-artifact@v3
+#        with:
+#          name: CoverageReports
+#          path: coverage-reports
+
+#      - name: 単体テストの結果表示
+#        shell: bash
+#        run: |
+#          echo '# Build Result :gear:' >> $GITHUB_STEP_SUMMARY
+#          cat build-result.txt >> $GITHUB_STEP_SUMMARY
+#          echo '' >> $GITHUB_STEP_SUMMARY
+#          echo '# Test Result :memo:' >> $GITHUB_STEP_SUMMARY
+#          cat testResult.txt | sed -n -e '/A total of/,/Passed/p' >> $GITHUB_STEP_SUMMARY
+#          echo '' >> $GITHUB_STEP_SUMMARY
+
+#      - name: コードカバレッジのサマリー作成
+#        uses: irongut/CodeCoverageSummary@v1.3.0
+#        with:
+#          filename: coverage-reports/**/coverage.*.cobertura.xml
+#          badge: true
+#          fail_below_min: true
+#          format: markdown
+#          hide_branch_rate: false
+#          hide_complexity: false
+#          indicators: true
+#          output: both
+#          thresholds: '60 80'
+
+#      - name: コードカバレッジの結果表示
+#        shell: bash
+#        run: |
+#          echo '# Coverage :triangular_ruler:' >> $GITHUB_STEP_SUMMARY
+#          cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
+
+#      - name: コードカバレッジの結果をPull-requestに表示
+#        uses: marocchino/sticky-pull-request-comment@v2
+#        if: github.event_name == 'pull_request'
+#        with:
+#          recreate: true
+#          path: code-coverage-results.md
 
   packaging:
     name: パッケージング
